# Generated by Django 4.1.1 on 2023-03-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_orderplaced_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
    ]
