# Generated by Django 4.1.1 on 2023-03-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
